name: Release Mac

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install pyinstaller
        run: python -m pip install -U pyinstaller
      - name: Build
        run: |
          cd src
          pyinstaller -F --clean ./timing_check.py
      - name: Copy files
        run: |
          mkdir oto-timing-check
          cp ./plugin/oto-timing-check.js ./oto-timing-check/
          cp ./plugin/plugin-unix.json ./oto-timing-check/plugin.json
          cp ./src/dist/timing_check ./oto-timing-check/
          cp ./resources/metronome.wav ./oto-timing-check/
      - name: Zip
        run: |
          VERSION=${{ github.ref_name }}
          echo $VERSION
          zip -r vlabeler-oto-timing-check-$VERSION-mac.zip ./oto-timing-check
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: vlabeler-oto-timing-check-${{ github.ref_name }}-mac.zip
